flotte-camion-net/Models/Commande/Commande.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TP3_NET.Models.Commun;

namespace TP3_NET.Models.Commande
{
    public class Commande
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdCommande { get; set; }
        public Client.Client Client { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime DateCommande { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime DepartSouhaitee { get; set; }

        public Adresse LieuDepart { get; set; }
        public Adresse LieuArrivee { get; set; }

        public Frequence Frequence { get; set; } = Frequence.NonApplicable;

        public List<Marchandise.Marchandise> Marchandises { get; set; }
    }
}

flotte-camion-net/Models/Commande/CommandeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TP3_NET.Models.Commande
{
    public class CommandeViewModel
    {
        public int IdCommande { get; set; }

        [DataType(DataType.Date)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "Veuillez saisir la date de la commande")]
        [Display(Name = "Date de commande", Description = "")]
        public DateTime DateCommande { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "Veuillez saisir la date de départ souhaitée")]
        [Display(Name = "Date de départ souhaitée", Description = "")]
        public DateTime DepartSouhaitee { get; set; }

        /*
         * Adresse de départ
         */

        public int IdAD { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Veuillez saisir la rue de départ")]
        [MaxLength(25, ErrorMessage = "La rue de départ ne peut comporter que 25 caractères maximum")]
        [Display(Name = "Rue", Prompt = "Rue de départ", Description = "")]
        public string RueAD { get; set; }

        [MaxLength(25, ErrorMessage = "Le complément d'adresse de départ ne peut contenir que 25 caractères")]
        [Display(Name = "Complément d'adresse", Prompt = "Complément d'adresse de départ", Description = "")]
        public string ComplementAD { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Veuillez saisir la ville de départ")]
        [MaxLength(25, ErrorMessage = "La ville de départ ne peut faire que 25 caractères maximum")]
        [Display(Name = "Ville", Prompt = "Ville de départ", Description = "")]
        public string VilleAD { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Veuillez saisir le pays de départ")]
        [MaxLength(25, ErrorMessage = "Le pays de départ ne peut faire que 25 caractères maximum")]
        [Display(Name = "Pays", Prompt = "Pays de départ", Description = "")]
        public string PaysAD { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Veuillez saisir le code postal de départ")]
        [MaxLength(10, ErrorMessage = "Le code postal ne peut contenir que 10 caractères maximum")]
        [Display(Name = "Code postal", Prompt = "Code postal de départ", Description = "")]
        public string CodePostalAD { get; set; }

        /*
         * Adresse d'arrivée
         */

        public int IdAA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Veuillez saisir la rue d'arrivée")]
        [MaxLength(25, ErrorMessage = "La rue d'arrivée ne peut comporter que 25 caractères maximum")]
        [Display(Name = "Rue", Prompt = "Rue d'arrivée", Description = "")]
        public string RueAA { get; set; }

        [MaxLength(25, ErrorMessage = "Le complément d'adresse d'arrivée ne peut contenir que 25 caractères")]
        [Display(Name = "Complément d'adresse", Prompt = "Complément d'adresse d'arrivée", Description = "")]
        public string ComplementAA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Veuillez saisir la ville d'arrivée")]
        [MaxLength(25, ErrorMessage = "La ville d'arrivée ne peut faire que 25 caractères maximum")]
        [Display(Name = "Ville", Prompt = "Ville d'arrivée", Description = "")]
        public string VilleAA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Veuillez saisir le pays d'arrivée")]
        [MaxLength(25, ErrorMessage = "Le pays d'arrivée ne peut faire que 25 caractères maximum")]
        [Display(Name = "Pays", Prompt = "Pays d'arrivée", Description = "")]
        public string PaysAA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Veuillez saisir le code postal d'arrivée")]
        [MaxLength(10, ErrorMessage = "Le code postal ne peut contenir que 10 caractères maximum")]
        [Display(Name = "Code postal", Prompt = "Code postal d'arrivée", Description = "")]
        public string CodePostalAA { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Veuillez choisir une fréquence")]
        [Display(Name = "Fréquence", Prompt = "Sélectionner une fréquence", Description = "")]
        public Frequence Frequence { get; set; } = Frequence.NonApplicable;

        public List<Marchandise.Marchandise> Marchandises { get; set; }

        public Commande ToCommande()
        {
            Commande commande = new Commande();
            commande.IdCommande = IdCommande;
            commande.DateCommande = DateCommande;
            commande.DepartSouhaitee = DepartSouhaitee;
            commande.Frequence = Frequence;
            commande.Marchandises = Marchandises;

            Commun.Adresse adresseDepart = new Commun.Adresse();
            adresseDepart.IdAdresse = IdAD;
            adresseDepart.CodePostal = CodePostalAD;
            adresseDepart.Pays = PaysAD;
            adresseDepart.Rue = RueAD;
            adresseDepart.Ville = VilleAD;

            Commun.Adresse adresseArrivee = new Commun.Adresse();
            adresseArrivee.IdAdresse = IdAA;
            adresseArrivee.CodePostal = CodePostalAA;
            adresseArrivee.Pays = PaysAA;
            adresseArrivee.Rue = RueAA;
            adresseArrivee.Ville = VilleAA;

            commande.LieuArrivee = adresseArrivee;
            commande.LieuDepart = adresseDepart;

            return commande;
        }

        public static CommandeViewModel FromCommande(Commande commande)
        {
            CommandeViewModel commandeViewModel = new CommandeViewModel();
            commandeViewModel.IdCommande = commande.IdCommande;
            commandeViewModel.DateCommande = commande.DateCommande;
            commandeViewModel.DepartSouhaitee = commande.DepartSouhaitee;
            commandeViewModel.Frequence = commande.Frequence;
            commandeViewModel.Marchandises = commande.Marchandises;

            Commun.Adresse adresseDepart = commande.LieuDepart;
            if (adresseDepart != null)
            {
                commandeViewModel.IdAD = adresseDepart.IdAdresse;
                commandeViewModel.CodePostalAD = adresseDepart.CodePostal;
                commandeViewModel.PaysAD = adresseDepart.Pays;
                commandeViewModel.RueAD = adresseDepart.Rue;
                commandeViewModel.VilleAD = adresseDepart.Ville;
            }

            Commun.Adresse adresseArrivee = commande.LieuArrivee;
            if (adresseArrivee != null)
            {
                commandeViewModel.IdAA = adresseArrivee.IdAdresse;
                commandeViewModel.CodePostalAA = adresseArrivee.CodePostal;
                commandeViewModel.PaysAA = adresseArrivee.Pays;
                commandeViewModel.RueAA = adresseArrivee.Rue;
                commandeViewModel.VilleAA = adresseArrivee.Ville;
            }

            return commandeViewModel;
        }
    }
}

flotte-camion-net/Models/Commande/Frequence.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TP3_NET.Models.Commande
{
    public enum Frequence
    {
        [Display(Name = "Non applicable")]
        NonApplicable = 1,

        [Display(Name = "Quotidien")]
        Quotidien = 2,

        [Display(Name = "Hebdomadaire")]
        Hebdomadaire = 3,

        [Display(Name = "Mensuel")]
        Mensuel = 4
    }
}

flotte-camion-net/Controllers/Commande/CommandeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using TP3_NET.Dao.Client;
using TP3_NET.Dao.Commande;
using TP3_NET.Dao.Livraison;
using TP3_NET.Models.Commande;

namespace TP3_NET.Controllers.Commande
{
    public class CommandeController : Controller
    {
        private readonly CommandeDao _commandeDao = new CommandeDao();
        private readonly LivraisonDao _livraisonDao = new LivraisonDao();
        private readonly ClientDao _clientDao = new ClientDao();

        public ActionResult Liste()
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsOperateur(Session))
            {
                var commandesVM = new List<CommandeViewModel>();

                foreach (Models.Commande.Commande commande in _commandeDao.GetList())
                {
                    commandesVM.Add(CommandeViewModel.FromCommande(commande));
                }

                return View(commandesVM);
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        public ActionResult MesCommandes()
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsClient(Session))
            {
                var idClient = _clientDao.FindByIdCompte((int)Session["compteID"]).IdClient;
                var commandesVM = new List<CommandeViewModel>();

                foreach (Models.Commande.Commande commande in _commandeDao.GetByClient(idClient))
                {
                    commandesVM.Add(CommandeViewModel.FromCommande(commande));
                }

                return View(commandesVM);
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        public ActionResult MaCommande(int id)
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsClient(Session))
            {
                if (id == 0)
                {
                    return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
                }

                var commandeVM = CommandeViewModel.FromCommande(_commandeDao.FindById(id));

                if (commandeVM == null)
                {
                    return HttpNotFound();
                }

                return View(commandeVM);
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        public ActionResult Consulter(int id)
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsOperateur(Session))
            {
                if (id == 0)
                {
                    return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
                }

                var commandeVM = CommandeViewModel.FromCommande(_commandeDao.FindById(id));

                if (commandeVM == null)
                {
                    return HttpNotFound();
                }

                return View(commandeVM);
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        public ActionResult Creer()
        {
            var commandeVM = CommandeViewModel.FromCommande(new Models.Commande.Commande());

            if (commandeVM == null)
            {
                return HttpNotFound();
            }

            commandeVM.DepartSouhaitee = DateTime.Today;

            return View(commandeVM);
        }

        public ActionResult Supprimer(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            var commandeVM = CommandeViewModel.FromCommande(_commandeDao.FindById(id));

            if (commandeVM == null)
            {
                return HttpNotFound();
            }

            return View(commandeVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreerPost(CommandeViewModel commandeVM)
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsIdentified(Session))
            {
                int compteId = (int)Session["compteID"];
                Models.Client.Client client = _clientDao.FindByIdCompte(compteId);

                commandeVM.Marchandises = (List<Models.Marchandise.Marchandise>)Session["marchandises"];

                if (commandeVM.DepartSouhaitee.Ticks < DateTime.Today.AddDays(1).Ticks)
                {
                    ModelState.AddModelError("DepartSouhaitee", "La date de départ ne peut pas être antérieure ou égale à aujourd'hui.");

                    return View("Creer", commandeVM);
                }

                if (commandeVM.Marchandises.Count < 1)
                {
                    ModelState.AddModelError("Marchandises", "Veuillez saisir au moins une marchandise.");

                    return View("Creer", commandeVM);
                }

                if (ModelState.IsValid)
                {
                    Models.Commande.Commande commande = commandeVM.ToCommande();

                    commande.DateCommande = DateTime.Now;
                    commande.Client = client;

                    foreach (Models.Marchandise.Marchandise marchandise in commande.Marchandises)
                    {
                        marchandise.IdCommande = commande.IdCommande;
                    }

                    commande = _commandeDao.Create(commande);

                    var marchandisesMaps = commandeVM.Marchandises
                        .GroupBy(
                            marchandise => marchandise.TypeMarchandise,
                            (typeMarchandise, marchandise) => new { TypeMarchandise = typeMarchandise, Marchandises = marchandise.ToList() }
                        );

                    Models.Livraison.Itineraire itineraire = new Models.Livraison.Itineraire();

                    itineraire.Adresses = new List<Models.Commun.Adresse>();
                    itineraire.Adresses.Add(commande.LieuDepart);
                    itineraire.Adresses.Add(commande.LieuArrivee);

                    foreach (var marchandiesMap in marchandisesMaps)
                    {
                        Models.Livraison.Livraison livraison = new Models.Livraison.Livraison();

                        livraison.Client = client;
                        livraison.Commande = commande;
                        livraison.Marchandises = new List<Models.Marchandise.Marchandise>();

                        foreach (Models.Marchandise.Marchandise marchandise in marchandiesMap.Marchandises)
                        {
                            marchandise.IdLivraison = livraison.IdLivraison;
                            livraison.Marchandises.Add(marchandise);
                        }

                        livraison.EtatLivraison = Models.Livraison.EtatLivraison.EnPreparation;
                        livraison.Itineraire = itineraire;

                        _livraisonDao.Create(livraison);
                    }
                }

                if (TP3_NET.Models.Service.IdentityService.SessionUserIsClient(Session))
                {
                    return RedirectToAction("MesCommandes");
                }
                else
                {
                    return RedirectToAction("Liste");
                }
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SupprimerPost(int id)
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsIdentified(Session))
            {
                if (id == 0)
                {
                    return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
                }

                _commandeDao.Remove(id);

                if (TP3_NET.Models.Service.IdentityService.SessionUserIsClient(Session))
                {
                    return RedirectToAction("MesCommandes");
                }
                else
                {
                    return RedirectToAction("Liste");
                }
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }
    }
}

flotte-camion-net/Views/Commande/Creer.cshtml
@model TP3_NET.Models.Commande.CommandeViewModel

@{
    ViewBag.Title = "Créer une commande";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Création d'une commande</h2>

@using (Html.BeginForm("CreerPost", "Commande"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Nouvelle commande</h4>
        <hr />
        @Html.ValidationSummary(true, "Le formulaire contient des erreurs, validation impossible.", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.DepartSouhaitee, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.DepartSouhaitee, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DepartSouhaitee, new { htmlAttributes = new { @class = "form-control", @type = "date", @value = DateTime.Today.AddDays(1).ToString("yyyy-MM-dd") } })
            @Html.ValidationMessageFor(model => model.DepartSouhaitee, "", new { @class = "text-danger" })
        </div>
    </div>

        <!-- Lieu de départ -->

        <p>Lieu de départ</p>

        <div class="form-group">
            @Html.LabelFor(model => model.RueAD, htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.RueAD, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.RueAD, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.RueAD, ViewData).Watermark } })
                @Html.ValidationMessageFor(model => model.RueAD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ComplementAD, htmlAttributes: new { @class = "control-label col-md-12" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.ComplementAD, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComplementAD, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.ComplementAD, ViewData).Watermark } })
                @Html.ValidationMessageFor(model => model.ComplementAD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VilleAD, htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.VilleAD, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.VilleAD, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.VilleAD, ViewData).Watermark } })
                @Html.ValidationMessageFor(model => model.VilleAD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaysAD, htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.PaysAD, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaysAD, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.PaysAD, ViewData).Watermark } })
                @Html.ValidationMessageFor(model => model.PaysAD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodePostalAD, htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.CodePostalAD, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodePostalAD, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.CodePostalAD, ViewData).Watermark } })
                @Html.ValidationMessageFor(model => model.CodePostalAD, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Lieu d'arrivée -->

        <p>Lieu d'arrivée</p>

        <div class="form-group">
            @Html.LabelFor(model => model.RueAA, htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.RueAA, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.RueAA, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.RueAA, ViewData).Watermark } })
                @Html.ValidationMessageFor(model => model.RueAA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ComplementAA, htmlAttributes: new { @class = "control-label col-md-12" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.ComplementAA, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComplementAA, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.ComplementAA, ViewData).Watermark } })
                @Html.ValidationMessageFor(model => model.ComplementAA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VilleAA, htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.VilleAA, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.VilleAA, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.VilleAA, ViewData).Watermark } })
                @Html.ValidationMessageFor(model => model.VilleAA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaysAA, htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.PaysAA, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaysAA, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.PaysAA, ViewData).Watermark } })
                @Html.ValidationMessageFor(model => model.PaysAA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodePostalAA, htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.CodePostalAA, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodePostalAA, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.CodePostalAA, ViewData).Watermark } })
                @Html.ValidationMessageFor(model => model.CodePostalAA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Frequence, htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            <div class="col-md-auto">
                <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.Frequence, ViewData).Description</small>
            </div>
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Frequence, new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.Frequence, ViewData).Watermark })
                @Html.ValidationMessageFor(model => model.Frequence, "", new { @class = "text-danger" })
            </div>
        </div>
        <button id="submit" type="submit" value="Modifier la commande" class="invisible"></button>
    </div>

    @Html.ValidationMessageFor(model => model.Marchandises, "", new { @class = "text-danger" })
}

@{
    Html.RenderAction("ListeModifiable", "Marchandise", new { marchandises = Model.Marchandises });
}

<hr />
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <button id="remote-submit" type="button" value="Passer la commande" class="btn btn-primary">
            Passer la commande
        </button>
    </div>
</div>

<div>
    @Html.ActionLink("Retour aux commandes", "Liste")
</div>

flotte-camion-net/Views/Commande/Liste.cshtml
@model IEnumerable<TP3_NET.Models.Commande.CommandeViewModel>

@{
    ViewBag.Title = "Liste des commandes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Liste des commandes</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DateCommande)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartSouhaitee)
        </th>
        <th>
            Ville de départ
        </th>
        <th>
            Ville d'arrivée
        </th>
        <th>
            Nombre de marchandises
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateCommande)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartSouhaitee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VilleAD)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VilleAA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marchandises.Count)
            </td>
            <td>
                @Html.ActionLink("Consulter", "Consulter", new { id = item.IdCommande }) | 
                @Html.ActionLink("Supprimer", "Supprimer", new { id = item.IdCommande })
            </td>
        </tr>
    }

</table>