flotte-camion-net/Models/Marchandise/Marchandise.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP3_NET.Models.Marchandise
{
    public class Marchandise
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdMarchandise { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Veuillez saisir le nom de la marchandise")]
        [MaxLength(25, ErrorMessage = "Le nom de la marchandise ne peut pas dépasser 25 caractères")]
        [Display(Name = "Nom", Prompt = "Insérer un nom", Description = "")]
        public string Nom { get; set; }

        [Range(1, 100, ErrorMessage = "Le volume de marchandise doit être situé entre 1 et 100m³")]
        [Required(ErrorMessage = "Veuillez saisir le volume de la marchandise")]
        [Display(Name = "Volume", Prompt = "Insérer un volume", Description = "")]
        public double Volume { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Veuillez choisir le type de la marchandise")]
        [Display(Name = "Type de marchandise", Prompt = "Sélectionner un type de marchandise", Description = "")]
        public TypeMarchandise TypeMarchandise { get; set; }

        public virtual Commande.Commande Commande { get; set; }
        public int IdCommande { get; set; }

        public virtual Livraison.Livraison Livraison { get; set; }
        public int? IdLivraison { get; set; }
    }
}

flotte-camion-net/Models/Marchandise/TypeMarchandise.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TP3_NET.Models.Marchandise
{
    public enum TypeMarchandise
    {
        [Display(Name = "Frais")]
        Frais = 1,

        [Display(Name = "Fragile")]
        Fragile = 2,

        [Display(Name = "Congelé")]
        Congele = 3,

        [Display(Name = "Animaux")]
        Animal = 4,

        [Display(Name = "Viande")]
        Viande = 5,

        [Display(Name = "Poisson")]
        Poisson = 6,

        [Display(Name = "Essence")]
        Essence = 7,

        [Display(Name = "Matériaux de construction")]
        MaterielConstruction = 8
    }
}

flotte-camion-net/Controllers/Marchandise/MarchandiseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP3_NET.Models.Marchandise;


namespace TP3_NET.Controllers.Marchandise
{
    public class MarchandiseController : Controller
    {
        public ActionResult ListeConsultable(IEnumerable<Models.Marchandise.Marchandise> marchandises)
        {
            Session["marchandises"] = new List<Models.Marchandise.Marchandise>(marchandises);

            return PartialView("_ListeConsultable", marchandises);
        }

        public ActionResult ListeModifiable(IEnumerable<Models.Marchandise.Marchandise> marchandises)
        {
            Session["marchandises"] = new List<Models.Marchandise.Marchandise>(marchandises);

            return PartialView("_ListeModifiable", marchandises);
        }

        public ActionResult Ajouter()
        {
            return PartialView("_Ajouter", new Models.Marchandise.Marchandise());
        }

        public ActionResult Modifier(Models.Marchandise.Marchandise marchandise, int idx)
        {
            return PartialView("_Modifier", new Models.Utilitaire.Paire<Models.Marchandise.Marchandise, int>(marchandise, idx));
        }

        public ActionResult Consulter(Models.Marchandise.Marchandise marchandise, int idx)
        {
            return PartialView("_Consulter", new Models.Utilitaire.Paire<Models.Marchandise.Marchandise, int>(marchandise, idx));
        }

        public ActionResult Supprimer(int idx)
        {
            return PartialView("_Supprimer", idx);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AjouterPost(Models.Marchandise.Marchandise marchandise)
        {
            List<Models.Marchandise.Marchandise> marchandises;

            if (Session["marchandises"] is List<Models.Marchandise.Marchandise>)
            {
                marchandises = (List<Models.Marchandise.Marchandise>)Session["marchandises"];
            }
            else
            {
                marchandises = new List<Models.Marchandise.Marchandise>();
            }

            if (ModelState.IsValid)
            {
                marchandises.Add(marchandise);

                Session["marchandises"] = marchandises;
            }

            return PartialView("_ListeModifiable", marchandises);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ModifierPost(Models.Utilitaire.Paire<Models.Marchandise.Marchandise, int> paireMarchandiseIdx)
        {
            List<Models.Marchandise.Marchandise> marchandises;

            if (Session["marchandises"] is List<Models.Marchandise.Marchandise>)
            {
                marchandises = (List<Models.Marchandise.Marchandise>)Session["marchandises"];
            }
            else
            {
                marchandises = new List<Models.Marchandise.Marchandise>();
            }

            if (ModelState.IsValid)
            {
                marchandises[paireMarchandiseIdx.Item2] = paireMarchandiseIdx.Item1;

                Session["marchandises"] = marchandises;
            }

            return PartialView("_ListeModifiable", marchandises);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SupprimerPost(int idx)
        {
            List<Models.Marchandise.Marchandise> marchandises;

            if (Session["marchandises"] is List<Models.Marchandise.Marchandise>)
            {
                marchandises = (List<Models.Marchandise.Marchandise>)Session["marchandises"];
            }
            else
            {
                marchandises = new List<Models.Marchandise.Marchandise>();
            }

            if (idx >= 0 && idx < marchandises.Count)
            {
                marchandises.RemoveAt(idx);

                Session["marchandises"] = marchandises;
            }
            else
            {
                return new HttpNotFoundResult();
            }

            return PartialView("_ListeModifiable", marchandises);
        }
    }
}

flotte-camion-net/Views/Marchandise/_Ajouter.cshtml
@model TP3_NET.Models.Marchandise.Marchandise

@{
    Layout = null;
}

@using (Ajax.BeginForm("AjouterPost", "Marchandise", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "marchandises", OnSuccess = "ajaxUnobstrusiveValidation" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.Nom, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.Nom, ViewData).Watermark } })
            @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TypeMarchandise, htmlAttributes: new { @class = "control-label col-md-2" })
        <br/>
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.TypeMarchandise, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.TypeMarchandise, ModelMetadata.FromLambdaExpression(model => model.TypeMarchandise, ViewData).Watermark, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TypeMarchandise, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Volume, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.Volume, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Volume, new { htmlAttributes = new { @class = "form-control", @type = "number", @placeholder = ModelMetadata.FromLambdaExpression(model => model.Volume, ViewData).Watermark } })
            @Html.ValidationMessageFor(model => model.Volume, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Ajouter la marchandise" class="btn btn-primary" />
        </div>
    </div>
 }

flotte-camion-net/Views/Marchandise/_Consulter.cshtml
@model TP3_NET.Models.Utilitaire.Paire<TP3_NET.Models.Marchandise.Marchandise, int>

@{
    Layout = null;
}

<h5>Marchandise @(Model.Item2 + 1)</h5>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Item1.Nom)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Item1.Nom)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Item1.TypeMarchandise)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Item1.TypeMarchandise)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Item1.Volume)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Item1.Volume)
    </dd>
</dl>

flotte-camion-net/Views/Marchandise/_ListeConsultable.cshtml
@model IEnumerable<TP3_NET.Models.Marchandise.Marchandise>

@{
    Layout = null;
}

<h4>Marchandises</h4>
<hr />

@{
    int idx = 0;
    foreach (var marchandise in Model)
    {
        Html.RenderAction("Consulter", "Marchandise", new { marchandise, idx });
        idx++;
    }
}

flotte-camion-net/Views/Marchandise/_ListeModifiable.cshtml
@model IEnumerable<TP3_NET.Models.Marchandise.Marchandise>

@{
    Layout = null;
}

<div id="marchandises">

    <h4>Marchandises</h4>
    <hr />

    @{
        int idx = 0;
        foreach (var marchandise in Model)
        {
            Html.RenderAction("Modifier", "Marchandise", new { marchandise, idx });
            Html.RenderAction("Supprimer", "Marchandise", new { idx });

            ++idx;
        }

        Html.RenderAction("Ajouter", "Marchandise");
    }

</div>

flotte-camion-net/Views/Marchandise/_Modifier.cshtml
@model TP3_NET.Models.Utilitaire.Paire<TP3_NET.Models.Marchandise.Marchandise, int>

@{
    Layout = null;
}

@using (Ajax.BeginForm("ModifierPost", "Marchandise", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "marchandises", OnSuccess = "ajaxUnobstrusiveValidation" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Item2)

    @Html.HiddenFor(model => model.Item1.IdMarchandise)

    <div class="form-group">
        @Html.LabelFor(model => model.Item1.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.Item1.Nom, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Item1.Nom, new { htmlAttributes = new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(model => model.Item1.Nom, ViewData).Watermark } })
            @Html.ValidationMessageFor(model => model.Item1.Nom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Item1.TypeMarchandise, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.Item1.TypeMarchandise, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Item1.TypeMarchandise, ModelMetadata.FromLambdaExpression(model => model.Item1.TypeMarchandise, ViewData).Watermark, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Item1.TypeMarchandise, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Item1.Volume, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.Item1.Volume, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Item1.Volume, new { htmlAttributes = new { @class = "form-control", @type = "number", @placeholder = ModelMetadata.FromLambdaExpression(model => model.Item1.Volume, ViewData).Watermark } })
            @Html.ValidationMessageFor(model => model.Item1.Volume, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Modifier la marchandise" class="btn btn-primary" />
        </div>
    </div>
}

flotte-camion-net/Views/Marchandise/_Supprimer.cshtml
@model  int

@{
    Layout = null;
}

@using (Ajax.BeginForm("SupprimerPost", "Marchandise", new { idx = Model }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "marchandises" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Supprimer la marchandise" class="btn btn-primary" />
        </div>
    </div>
}