flotte-camion-net/Models/Livraison/EtatLivraison.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TP3_NET.Models.Livraison
{
    public enum EtatLivraison
    {
        [Display(Name = "En préparation")]
        EnPreparation = 1,

        [Display(Name = "En cours")]
        EnCours = 2,

        [Display(Name = "Livrée")]
        Livree = 3
    }
}

flotte-camion-net/Models/Livraison/Itineraire.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TP3_NET.Models.Commun;

namespace TP3_NET.Models.Livraison
{
    public class Itineraire
    {
        [Key] public int IdItineraire { get; set; }

        public List<Adresse> Adresses { get; set; }
    }
}

flotte-camion-net/Models/Livraison/Livraison.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TP3_NET.Models.Camion;
using TP3_NET.Models.Employe;

namespace TP3_NET.Models.Livraison
{
    public class Livraison
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdLivraison { get; set; }

        [ForeignKey("IdCommande")]
        public Commande.Commande Commande { get; set; }
        public int IdCommande { get; set; }

        public List<Marchandise.Marchandise> Marchandises { get; set; }

        [ForeignKey("IdClient")]
        public Client.Client Client { get; set; }
        public int IdClient { get; set; }

        public Conducteur Conducteur { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime DateDepart { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime DateArrivee { get; set; }

        public Camion.Camion Camion { get; set; }

        public Remorque Remorque { get; set; }

        public EtatLivraison EtatLivraison { get; set; } = EtatLivraison.EnPreparation;

        [ForeignKey("IdItineraire")]
        public Itineraire Itineraire { get; set; }
        public int IdItineraire { get; set; }
    }
}

flotte-camion-net/Models/Livraison/LivraisonViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TP3_NET.Models.Livraison
{
    public class LivraisonViewModel
    {
        [Required]
        public int IdLivraison { get; set; }

        [Display(Name = "Commande", Description = "")]
        public int IdCommande { get; set; }

        [Display(Name = "Client", Description = "")]
        public int IdClient { get; set; }

        [Display(Name = "Nb. marchandises", Description = "")]
        public int NbMarchandises { get; set; }

        [Required(ErrorMessage = "Veuillez sélectionner un conducteur")]
        [Display(Name = "Conducteur", Prompt = "Sélectionner un conducteur", Description = "")]
        public int IdConducteur { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "Veuillez saisir la date de départ")]
        [Display(Name = "Date de départ", Description = "")]
        public DateTime DateDepart { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "Veuillez saisir la date d'arrivée")]
        [Display(Name = "Date d'arrivée", Description = "")]
        public DateTime DateArrivee { get; set; }

        [Required(ErrorMessage = "Veuillez sélectionner un camion")]
        [Display(Name = "Camion", Prompt = "Sélectionner un camion", Description = "")]
        public int IdCamion { get; set; }

        [Required(ErrorMessage = "Veuillez sélectionner une remorque")]
        [Display(Name = "Remorque", Prompt = "Sélectionner une remorque", Description = "")]
        public int IdRemorque { get; set; }

        [Display(Name = "État de la livraison", Description = "")]
        public EtatLivraison EtatLivraison { get; set; } = EtatLivraison.EnPreparation;

        [Display(Name = "Itinéraire", Description = "")]
        public string Itineraire { get; set; }
        public int IdItineraire { get; set; }

        public static LivraisonViewModel FromLivraison(Livraison livraison)
        {
            LivraisonViewModel livraisonViewModel = new LivraisonViewModel();

            livraisonViewModel.IdCamion = (livraison.Camion == null) ? 0 : livraison.Camion.IdCamion;
            livraisonViewModel.IdClient = livraison.Client.IdClient;
            livraisonViewModel.IdCommande = livraison.Commande.IdCommande;
            livraisonViewModel.NbMarchandises = livraison.Marchandises.Count;
            livraisonViewModel.IdConducteur = (livraison.Conducteur == null) ? 0 : livraison.Conducteur.IdEmploye; 
            livraisonViewModel.DateArrivee = livraison.DateArrivee;
            livraisonViewModel.DateDepart = livraison.DateDepart;
            livraisonViewModel.EtatLivraison = livraison.EtatLivraison;
            livraisonViewModel.IdLivraison = livraison.IdLivraison;
            livraisonViewModel.Itineraire = (livraison.Itineraire.Adresses.Count > 2) ? livraison.Itineraire.Adresses[0].Ville + " -> " + livraison.Itineraire.Adresses[livraison.Itineraire.Adresses.Count - 1].Ville : "Itinéraire indéterminable";
            livraisonViewModel.IdItineraire = (livraison.Itineraire == null) ? 0 : livraison.Itineraire.IdItineraire;
            livraisonViewModel.IdRemorque = (livraison.Remorque == null) ? 0 : livraison.Remorque.IdRemorque;

            return livraisonViewModel;
        }
    }
}

flotte-camion-net/Controllers/Livraison/LivraisonController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using TP3_NET.Dao.Livraison;
using TP3_NET.Dao.Vehicule;
using TP3_NET.Dao.Employe;
using System.Linq;
using TP3_NET.Dao.Client;

namespace TP3_NET.Controllers.Livraison
{
    public class LivraisonController : Controller
    {
        private readonly ClientDao _clientDao = new ClientDao();
        private readonly LivraisonDao _livraisonDao = new LivraisonDao();
        private readonly CamionDao _camionDao = new CamionDao();
        private readonly ConducteurDao _conducteurDao = new ConducteurDao();
        private readonly RemorqueDao _remorqueDao = new RemorqueDao();

        public ActionResult Liste()
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsOperateur(Session))
            {
                var livraisonsVM = new List<Models.Livraison.LivraisonViewModel>();

                foreach (Models.Livraison.Livraison livraison in _livraisonDao.GetList())
                {
                    livraisonsVM.Add(Models.Livraison.LivraisonViewModel.FromLivraison(livraison));
                }

                return View(livraisonsVM);
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        public ActionResult MesLivraisons()
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsClient(Session))
            {
                var idClient = _clientDao.FindByIdCompte((int)Session["compteID"]).IdClient;
                var livraisonsVM = new List<Models.Livraison.LivraisonViewModel>();

                foreach (Models.Livraison.Livraison livraison in _livraisonDao.GetByClient(idClient))
                {
                    livraisonsVM.Add(Models.Livraison.LivraisonViewModel.FromLivraison(livraison));
                }

                return View(livraisonsVM);
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        public ActionResult MaLivraison(int id)
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsClient(Session))
            {
                if (id == 0)
                {
                    return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
                }

                var livraison = _livraisonDao.FindById(id);

                if (livraison == null)
                {
                    return HttpNotFound();
                }

                return View(Models.Livraison.LivraisonViewModel.FromLivraison(livraison));
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        public ActionResult Consulter(int id)
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsOperateur(Session))
            {
                if (id == 0)
                {
                    return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
                }

                var livraison = _livraisonDao.FindById(id);

                if (livraison == null)
                {
                    return HttpNotFound();
                }

                return View(Models.Livraison.LivraisonViewModel.FromLivraison(livraison));
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        public ActionResult Confirmer(int id)
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsOperateur(Session))
            {
                if (id == 0)
                {
                    return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
                }

                var livraison = _livraisonDao.FindById(id);
                var livraisonVM = Models.Livraison.LivraisonViewModel.FromLivraison(livraison);

                if (livraisonVM == null)
                {
                    return HttpNotFound();
                }

                livraisonVM.DateDepart = livraison.Commande.DepartSouhaitee;
                livraisonVM.DateArrivee = livraisonVM.DateDepart.AddDays(1);
                Session["MarchandisesLivraison"] = livraison.Marchandises;

                IEnumerable<SelectListItem> camionsItems = from camion in _camionDao.GetList()
                    select new SelectListItem
                    {
                        Value = camion.IdCamion.ToString(),
                        Text = "Camion n°" + camion.IdCamion.ToString()
                    };

                Session["CamionsItems"] = camionsItems;

                IEnumerable<SelectListItem> conducteursItems = from conducteur in _conducteurDao.GetList()
                    select new SelectListItem
                    {
                        Value = conducteur.IdEmploye.ToString(),
                        Text = "Employé n°" + conducteur.IdEmploye.ToString()
                    };

                Session["ConducteursItems"] = conducteursItems;

                IEnumerable<SelectListItem> remorquesItems = from remorque in _remorqueDao.GetList()
                    select new SelectListItem
                    {
                        Value = remorque.IdRemorque.ToString(),
                        Text = "Remorque n°" + remorque.IdRemorque.ToString()
                    };

                Session["RemorquesItems"] = remorquesItems;


                return View(livraisonVM);
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmerPost(Models.Livraison.LivraisonViewModel livraisonVM)
        {
            if (TP3_NET.Models.Service.IdentityService.SessionUserIsOperateur(Session))
            {
                Models.Livraison.Livraison livraison = _livraisonDao.FindById(livraisonVM.IdLivraison);

                if (livraisonVM.DateDepart.Ticks < livraison.Commande.DepartSouhaitee.Ticks)
                {
                    ModelState.AddModelError("DateDepart", "La date de départ ne peut pas être antérieure à la date souhaitée par le client.");

                    return View("Confirmer", livraisonVM);
                }

                if (livraisonVM.DateArrivee.Ticks < livraisonVM.DateDepart.Ticks)
                {
                    ModelState.AddModelError("DateArrivee", "La date d'arrivée ne peut pas être antérieure à la date de départ.");

                    return View("Confirmer", livraisonVM);
                }

                livraison.Camion = _camionDao.FindById(livraisonVM.IdCamion);
                livraison.Conducteur = _conducteurDao.FindById(livraisonVM.IdConducteur);
                livraison.Remorque = _remorqueDao.FindById(livraisonVM.IdRemorque);
                livraison.DateArrivee = livraisonVM.DateArrivee;
                livraison.DateDepart = livraisonVM.DateDepart;
                livraison.EtatLivraison = Models.Livraison.EtatLivraison.EnCours;

                if (ModelState.IsValid)
                {
                    _livraisonDao.Update(livraison.IdLivraison, livraison);
                }

                return RedirectToAction("Liste");
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }
    }
}

flotte-camion-net/Views/Livraison/Confirmer.cshtml
@model TP3_NET.Models.Livraison.LivraisonViewModel

@{
    ViewBag.Title = "Confirmation de livraison";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Confirmation de la livraison n°@Model.IdLivraison</h2>

@using (Html.BeginForm("ConfirmerPost", "Livraison"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "Le formulaire contient des erreurs, validation impossible.", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.IdLivraison)
    @Html.HiddenFor(model => model.IdClient)
    @Html.HiddenFor(model => model.IdCommande)
    @Html.HiddenFor(model => model.IdItineraire)

    <p>
        <a class="btn btn-primary" data-toggle="collapse" href="#informations" role="button" aria-expanded="false" aria-controls="informations">Informations de la livraison</a>
    </p>
    <div class="collapse multi-collapse" id="informations">
        <div class="card card-body">

            <!-- IdClient -->

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.IdClient)
                </dt>
                <dd>
                    @(new HtmlString("Client n°" + Model.IdClient))
                </dd>
            </dl>

            <!-- IdCommande -->

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.IdCommande)
                </dt>
                <dd>
                    @Html.ActionLink("Commande n°" + Model.IdCommande, "Consulter", "Commande", new { id = Model.IdCommande }, null)
                </dd>
            </dl>

            <!-- Marchandises -->

            @{
                List<TP3_NET.Models.Marchandise.Marchandise> marchandisesLivraison = Session["MarchandisesLivraison"] as List<TP3_NET.Models.Marchandise.Marchandise>;
                Html.RenderAction("ListeConsultable", "Marchandise", new { marchandises = marchandisesLivraison });
            }
        </div>
    </div>

    <!-- DateDepart -->

    <div class="form-group">
        @Html.LabelFor(model => model.DateDepart, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.DateDepart, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateDepart, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.DateDepart, "", new { @class = "text-danger" })
        </div>
    </div>

    <!-- DateArrivee -->

    <div class="form-group">
        @Html.LabelFor(model => model.DateArrivee, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.DateArrivee, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateArrivee, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.DateArrivee, "", new { @class = "text-danger" })
        </div>
    </div>

    <!-- Conducteur -->

    @{
        IEnumerable<SelectListItem> conducteursItems = Session["ConducteursItems"] as IEnumerable<SelectListItem>;
    }

    <div class="form-group">
        @Html.LabelFor(model => model.IdConducteur, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.IdConducteur, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.IdConducteur, new SelectList(conducteursItems, "Value", "Text"), ModelMetadata.FromLambdaExpression(model => model.IdConducteur, ViewData).Watermark, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdConducteur, "", new { @class = "text-danger" })
        </div>
    </div>

    <!-- Camion -->

    @{
        IEnumerable<SelectListItem> camionsItems = Session["CamionsItems"] as IEnumerable<SelectListItem>;
    }

    <div class="form-group">
        @Html.LabelFor(model => model.IdCamion, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.IdCamion, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.IdCamion, new SelectList(camionsItems, "Value", "Text"), ModelMetadata.FromLambdaExpression(model => model.IdCamion, ViewData).Watermark, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCamion, "", new { @class = "text-danger" })
        </div>
    </div>

    <!-- Remorque -->

    @{
        IEnumerable<SelectListItem> remorquesItems = Session["RemorquesItems"] as IEnumerable<SelectListItem>;
    }

    <div class="form-group">
        @Html.LabelFor(model => model.IdRemorque, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.IdRemorque, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.IdRemorque, new SelectList(remorquesItems, "Value", "Text"), ModelMetadata.FromLambdaExpression(model => model.IdRemorque, ViewData).Watermark, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdRemorque, "", new { @class = "text-danger" })
        </div>
    </div>

    <!-- Itineraire -->

    <div class="form-group">
        @Html.LabelFor(model => model.Itineraire, htmlAttributes: new { @class = "control-label col-md-2" })
        <br />
        <div class="col-md-auto">
            <small class="text-muted">@ModelMetadata.FromLambdaExpression(model => model.Itineraire, ViewData).Description</small>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Itineraire, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    <input id="submit" type="submit" value="Confirmer la livraison" class="btn btn-primary" />
</div>
}

<div>
    @Html.ActionLink("Retour aux livraisons", "Liste")
</div>

flotte-camion-net/Views/Livraison/Consulter.cshtml
@model TP3_NET.Models.Livraison.LivraisonViewModel

@{
    ViewBag.Title = "Consultation de livraison";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Livraison n°@Model.IdLivraison</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdClient)
        </dt>
        <dd>
            @(new HtmlString("Client n°" + Model.IdClient))
        </dd>
    </dl>

    @{
        List<TP3_NET.Models.Marchandise.Marchandise> marchandisesLivraison = Session["MarchandisesLivraison"] as List<TP3_NET.Models.Marchandise.Marchandise>;
        Html.RenderAction("ListeConsultable", "Marchandise", new { marchandises = marchandisesLivraison });
    }

    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.IdCommande)
        </dt>
        <dd>
            @Html.ActionLink("Commande n°" + Model.IdCommande, "Consulter", "Commande", new { id = Model.IdCommande }, null)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdConducteur)
        </dt>
        <dd>
            @((Model.IdConducteur == 0) ? new HtmlString("À définir") : @Html.ActionLink("Employé n° " + Model.IdConducteur, "Consulter", "Conducteur", new { id = Model.IdConducteur }, null))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateDepart)
        </dt>
        <dd>
            @((Model.DateDepart == default(DateTime)) ? new HtmlString("À définir") : Html.DisplayFor(model => model.DateDepart))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateArrivee)
        </dt>
        <dd>
            @((Model.DateArrivee == default(DateTime)) ? new HtmlString("À définir") : Html.DisplayFor(model => model.DateArrivee))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdCamion)
        </dt>
        <dd>
            @((Model.IdCamion == 0) ? new HtmlString("À définir") : Html.ActionLink("Camion n°" + Model.IdCamion, "Consulter", "Camion", new { id = Model.IdCamion }, null))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdRemorque)
        </dt>

        <dd>
            @((Model.IdRemorque == 0) ? new HtmlString("À définir") : Html.ActionLink("Remorque n°" + Model.IdRemorque, "Consulter", "Remorque", new { id = Model.IdRemorque }, null))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EtatLivraison)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EtatLivraison)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Itineraire)
        </dt>
        <dd>
            @Model.Itineraire
        </dd>
    </dl>
    </div>
    <p>
        @Html.ActionLink("Confirmer", "Confirmer", new { id = Model.IdLivraison }) |
        @Html.ActionLink("Retour aux livraisons", "Liste")
    </p>

flotte-camion-net/Views/Livraison/Liste.cshtml
@model IEnumerable<TP3_NET.Models.Livraison.LivraisonViewModel>

@{
    ViewBag.Title = "Liste des commandes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Livraisons</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdCommande);
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdClient)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NbMarchandises)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateDepart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateArrivee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EtatLivraison)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.ActionLink("Commande n°" + item.IdCommande, "Consulter", "Commande", new { id = item.IdCommande }, null)
        </td>
        <td>
            @("Client n°" + item.IdClient)
        </td>
        <th>
            @item.NbMarchandises
        </th>
        <td>
            @((item.DateDepart == default(DateTime)) ? new HtmlString("À définir") : Html.DisplayFor(modelItem => item.DateDepart))
        </td>
        <td>
            @((item.DateArrivee == default(DateTime)) ? new HtmlString("À définir") : Html.DisplayFor(modelItem => item.DateArrivee))
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EtatLivraison)
        </td>
        <td>
            @Html.ActionLink("Confirmer", "Confirmer", new { id = item.IdLivraison }, htmlAttributes: new { @class = (item.EtatLivraison == TP3_NET.Models.Livraison.EtatLivraison.EnPreparation) ? "" : "disabled" }) | 
            @Html.ActionLink("Consulter", "Consulter", new { id = item.IdLivraison })
        </td>
    </tr>
    }

</table>

flotte-camion-net/Views/Livraison/MaLivraison.cshtml
@model TP3_NET.Models.Livraison.LivraisonViewModel

@{
    ViewBag.Title = "Consultation de livraison";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Livraison n°@Model.IdLivraison</h2>

<div>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.IdCommande)
        </dt>
        <dd>
            @Html.ActionLink("Commande n°" + Model.IdCommande, "MaCommande", "Commande", new { id = Model.IdCommande }, null)
        </dd>

        @{
            List<TP3_NET.Models.Marchandise.Marchandise> marchandisesLivraison = Session["MarchandisesLivraison"] as List<TP3_NET.Models.Marchandise.Marchandise>;
            Html.RenderAction("ListeConsultable", "Marchandise", new { marchandises = marchandisesLivraison });
        }

        <dt>
            @Html.DisplayNameFor(model => model.DateDepart)
        </dt>
        <dd>
            @((Model.DateDepart == default(DateTime)) ? new HtmlString("En attente") : Html.DisplayFor(model => model.DateDepart))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateArrivee)
        </dt>
        <dd>
            @((Model.DateArrivee == default(DateTime)) ? new HtmlString("En attente") : Html.DisplayFor(model => model.DateArrivee))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EtatLivraison)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EtatLivraison)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Itineraire)
        </dt>
        <dd>
            @Model.Itineraire
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Retour à mes livraisons", "MesLivraisons")
</p>

flotte-camion-net/Views/Livraison/MesLivraisons.cshtml
@model IEnumerable<TP3_NET.Models.Livraison.LivraisonViewModel>

@{
    ViewBag.Title = "Liste des commandes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mes livraisons</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdCommande)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NbMarchandises)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateDepart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateArrivee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EtatLivraison)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink("Commande n°" + item.IdCommande, "MaCommande", "Commande", new { id = item.IdCommande }, null)
            </td>
            <th>
                @item.NbMarchandises
            </th>
            <td>
                @((item.DateDepart == default(DateTime)) ? new HtmlString("En attente") : Html.DisplayFor(modelItem => item.DateDepart))
            </td>
            <td>
                @((item.DateArrivee == default(DateTime)) ? new HtmlString("En attente") : Html.DisplayFor(modelItem => item.DateArrivee))
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EtatLivraison)
            </td>
            <td>
                @Html.ActionLink("Consulter", "MaLivraison", new { id = item.IdLivraison })
            </td>
        </tr>
    }

</table>